# -*- coding: utf-8 -*-
"""ACADEMIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NLwwawLFnBNa-qCL0VrrCtji02Y78cyG
"""

import random
import math
import json
from datetime import datetime
from pathlib import Path

courses = {
    "AID": "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
    "CSE IN AI": "COMPUTER SCIENCE ENGINEERING IN ARTIFICIAL INTELLIGENCE",
    "AIM": "ARTIFICIAL INTELLIGENCE IN MEDICAL ENGINEERING",
    "AARS": "ARTIFICIAL INTELLIGENCE IN ROBOTICS",
    "AIQ": "ARTIFICIAL INTELLIGENCE IN QUANTUM TECHNOLOGY",
    "CSE": "COMPUTER SCIENCE AND ENGINEERING",
    "IT": "INFORMATION TECHNOLOGY",
    "ECE": "ELECTRONICS AND COMMUNICATION ENGINEERING",
    "EEE": "ELECTRICAL AND ELECTRONICS ENGINEERING",
    "EE": "ELECTRICAL ENGINEERING",
    "ME": "MECHANICAL ENGINEERING",
    "CE": "CIVIL ENGINEERING",
    "CHE": "CHEMICAL ENGINEERING",
    "AE": "AEROSPACE ENGINEERING",
    "AERO": "AERONAUTICAL ENGINEERING",
    "AUTO": "AUTOMOBILE ENGINEERING",
    "AIML": "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING",
    "DS": "DATA SCIENCE",
    "CYBER": "CYBER SECURITY",
    "CSBS": "COMPUTER SCIENCE AND BUSINESS SYSTEMS",
    "CSSE": "COMPUTER SCIENCE AND SOFTWARE ENGINEERING",
    "CSE IOT": "COMPUTER SCIENCE AND ENGINEERING IN INTERNET OF THINGS",
    "CSE DS": "COMPUTER SCIENCE AND ENGINEERING IN DATA SCIENCE",
    "CSE CY": "COMPUTER SCIENCE AND ENGINEERING IN CYBER SECURITY",
    "CSE BD": "COMPUTER SCIENCE AND ENGINEERING IN BIG DATA",
    "VLSI": "VLSI DESIGN AND TECHNOLOGY",
    "EI": "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
    "ICE": "INSTRUMENTATION AND CONTROL ENGINEERING",
    "EIE": "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
    "EMBED": "EMBEDDED SYSTEMS ENGINEERING",
    "MECHATRONICS": "MECHATRONICS ENGINEERING",
    "ROBOTICS": "ROBOTICS ENGINEERING",
    "BIOMED": "BIOMEDICAL ENGINEERING",
    "BIOTECH": "BIOTECHNOLOGY ENGINEERING",
    "ENV": "ENVIRONMENTAL ENGINEERING",
    "MATERIALS": "MATERIALS ENGINEERING",
    "NANO": "NANOTECHNOLOGY ENGINEERING",
    "PETRO": "PETROLEUM ENGINEERING",
    "MINING": "MINING ENGINEERING",
    "MARINE": "MARINE ENGINEERING",
    "AGRI": "AGRICULTURAL ENGINEERING",
    "FOOD": "FOOD TECHNOLOGY",
    "TEXTILE": "TEXTILE ENGINEERING",
    "INDUSTRIAL": "INDUSTRIAL ENGINEERING",
    "PRODUCTION": "PRODUCTION ENGINEERING",
    "MANUFACTURING": "MANUFACTURING ENGINEERING",
    "SUSTAIN": "SUSTAINABLE ENGINEERING",
    "ENERGY": "ENERGY ENGINEERING",
    "QUANTUM": "QUANTUM ENGINEERING",
    "SPACE": "SPACE ENGINEERING"
}

course_subjects = {
    "AID": ["MATHEMATICS (LINEAR ALGEBRA, CALCULUS, PROBABILITY)", "PYTHON PROGRAMMING", "DATA STRUCTURES", "STATISTICS", "MACHINE LEARNING BASICS", "DATA ANALYSIS"],
    "CSE IN AI": ["MATHEMATICS (LINEAR ALGEBRA, CALCULUS)", "PROGRAMMING (PYTHON/C++)", "DATA STRUCTURES AND ALGORITHMS", "DISCRETE MATHEMATICS", "MACHINE LEARNING BASICS", "COMPUTER SYSTEM BASICS"],
    "AIM": ["MATHEMATICS (CALCULUS)", "PYTHON PROGRAMMING", "BIOLOGY BASICS", "SIGNAL PROCESSING INTRODUCTION", "MACHINE LEARNING BASICS", "MEDICAL DATA ANALYSIS"],
    "AARS": ["MATHEMATICS (CALCULUS, LINEAR ALGEBRA)", "PROGRAMMING (PYTHON/C++)", "PHYSICS (MECHANICS)", "CONTROL SYSTEM BASICS", "EMBEDDED SYSTEMS", "ROBOTICS FUNDAMENTALS"],
    "AIQ": ["MATHEMATICS (LINEAR ALGEBRA, PROBABILITY)", "PROGRAMMING (PYTHON)", "CLASSICAL PHYSICS", "INTRODUCTION TO QUANTUM MECHANICS", "ALGORITHMIC THINKING", "QUANTUM COMPUTING BASICS"],
    "CSE": ["DISCRETE MATHEMATICS", "PROGRAMMING (C/PYTHON)", "DATA STRUCTURES", "COMPUTER ORGANIZATION", "OPERATING SYSTEM BASICS", "ALGORITHMIC THINKING"],
    "IT": ["PROGRAMMING BASICS", "DATABASE FUNDAMENTALS", "NETWORKING BASICS", "WEB TECHNOLOGIES", "DATA STRUCTURES", "SYSTEM ADMINISTRATION BASICS"],
    "ECE": ["MATHEMATICS (CALCULUS)", "PHYSICS (ELECTROMAGNETISM)", "BASIC ELECTRONICS", "DIGITAL LOGIC", "SIGNAL PROCESSING BASICS", "COMMUNICATION SYSTEM FUNDAMENTALS"],
    "EEE": ["MATHEMATICS (CALCULUS)", "PHYSICS (ELECTRICITY)", "CIRCUIT THEORY", "POWER SYSTEM BASICS", "CONTROL SYSTEM BASICS", "ELECTRICAL MACHINES INTRODUCTION"],
    "EE": ["MATHEMATICS (CALCULUS)", "PHYSICS (ELECTRICITY)", "CIRCUIT ANALYSIS", "POWER SYSTEM BASICS", "CONTROL THEORY INTRODUCTION", "ELECTRICAL MACHINES"],
    "ME": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "ENGINEERING DRAWING", "THERMODYNAMICS BASICS", "MATERIAL SCIENCE", "MECHANICS OF SOLIDS"],
    "CE": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "ENGINEERING DRAWING", "STRUCTURAL MECHANICS", "FLUID MECHANICS", "CONSTRUCTION MATERIALS"],
    "CHE": ["MATHEMATICS (CALCULUS)", "CHEMISTRY FUNDAMENTALS", "THERMODYNAMICS", "FLUID MECHANICS", "CHEMICAL PROCESS PRINCIPLES", "MASS TRANSFER BASICS"],
    "AE": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "FLUID DYNAMICS", "THERMODYNAMICS", "AIRCRAFT STRUCTURES BASICS", "PROPULSION FUNDAMENTALS"],
    "AERO": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "FLUID MECHANICS", "THERMODYNAMICS", "AIRCRAFT DESIGN BASICS", "PROPULSION SYSTEM BASICS"],
    "AUTO": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "ENGINE MECHANICS", "THERMODYNAMICS", "AUTOMOTIVE SYSTEM BASICS", "MATERIAL SCIENCE"],
    "AIML": ["MATHEMATICS (LINEAR ALGEBRA, PROBABILITY)", "PYTHON PROGRAMMING", "DATA STRUCTURES", "STATISTICS", "MACHINE LEARNING", "DATA ANALYTICS"],
    "DS": ["MATHEMATICS (STATISTICS, LINEAR ALGEBRA)", "PYTHON/R PROGRAMMING", "DATA STRUCTURES", "PROBABILITY THEORY", "DATA VISUALIZATION", "DATA ANALYSIS"],
    "CYBER": ["PROGRAMMING (C/PYTHON)", "NETWORKING BASICS", "OPERATING SYSTEM BASICS", "CRYPTOGRAPHY INTRODUCTION", "SYSTEM SECURITY BASICS", "ETHICAL HACKING FUNDAMENTALS"],
    "CSBS": ["PROGRAMMING BASICS", "DATA STRUCTURES", "BUSINESS ANALYTICS", "DATABASE MANAGEMENT", "STATISTICS", "INFORMATION SYSTEM BASICS"],
    "CSSE": ["PROGRAMMING (JAVA/C++)", "DATA STRUCTURES", "SOFTWARE DESIGN PRINCIPLES", "DATABASE BASICS", "OPERATING SYSTEM BASICS", "SOFTWARE ENGINEERING FUNDAMENTALS"],
    "CSE IOT": ["PROGRAMMING (C/PYTHON)", "EMBEDDED SYSTEM BASICS", "NETWORKING BASICS", "SENSOR TECHNOLOGY", "DATA STRUCTURES", "IOT ARCHITECTURE"],
    "CSE DS": ["MATHEMATICS (STATISTICS)", "PYTHON PROGRAMMING", "DATA STRUCTURES", "DATA ANALYTICS", "MACHINE LEARNING BASICS", "DATA VISUALIZATION"],
    "CSE CY": ["PROGRAMMING BASICS", "NETWORK SECURITY", "OPERATING SYSTEM BASICS", "CRYPTOGRAPHY", "SYSTEM SECURITY", "ETHICAL HACKING"],
    "CSE BD": ["PYTHON PROGRAMMING", "DATA STRUCTURES", "DATABASE SYSTEMS", "BIG DATA BASICS", "DISTRIBUTED SYSTEMS", "DATA ANALYTICS"],
    "VLSI": ["MATHEMATICS (LINEAR ALGEBRA)", "SEMICONDUCTOR PHYSICS", "DIGITAL ELECTRONICS", "ANALOG ELECTRONICS", "CMOS DESIGN BASICS", "IC FABRICATION INTRODUCTION"],
    "EI": ["MATHEMATICS (CALCULUS)", "PHYSICS (ELECTRONICS)", "CIRCUIT THEORY", "INSTRUMENTATION BASICS", "CONTROL SYSTEMS", "SIGNAL PROCESSING"],
    "ICE": ["MATHEMATICS (CALCULUS)", "CIRCUIT THEORY", "CONTROL SYSTEM BASICS", "PROCESS CONTROL", "INSTRUMENTATION", "SIGNAL PROCESSING"],
    "EIE": ["MATHEMATICS (CALCULUS)", "BASIC ELECTRONICS", "CIRCUIT THEORY", "INSTRUMENTATION BASICS", "CONTROL SYSTEM BASICS", "SIGNAL PROCESSING"],
    "EMBED": ["PROGRAMMING (C)", "DIGITAL ELECTRONICS", "MICROCONTROLLERS", "REAL TIME SYSTEMS", "SENSOR INTERFACING", "EMBEDDED SYSTEM DESIGN"],
    "MECHATRONICS": ["MATHEMATICS (CALCULUS)", "MECHANICS", "ELECTRONICS BASICS", "CONTROL SYSTEM BASICS", "EMBEDDED SYSTEMS", "ROBOTICS FUNDAMENTALS"],
    "ROBOTICS": ["MATHEMATICS (LINEAR ALGEBRA)", "PROGRAMMING (PYTHON/C++)", "MECHANICS", "CONTROL SYSTEMS", "SENSOR TECHNOLOGY", "ROBOT KINEMATICS"],
    "BIOMED": ["BIOLOGY BASICS", "PHYSICS (ELECTRONICS)", "SIGNAL PROCESSING", "MEDICAL INSTRUMENTATION", "BIOMATERIALS", "BIOMECHANICS"],
    "BIOTECH": ["BIOLOGY (MOLECULAR BIOLOGY)", "CHEMISTRY BASICS", "GENETICS", "BIOCHEMISTRY", "CELL BIOLOGY", "BIOINFORMATICS INTRODUCTION"],
    "ENV": ["CHEMISTRY BASICS", "ECOLOGY", "FLUID MECHANICS", "ENVIRONMENTAL SCIENCE", "WASTE MANAGEMENT", "POLLUTION CONTROL"],
    "MATERIALS": ["CHEMISTRY BASICS", "PHYSICS (SOLID STATE)", "THERMODYNAMICS", "MATERIAL STRUCTURE", "METALLURGY", "MATERIAL CHARACTERIZATION"],
    "NANO": ["PHYSICS (QUANTUM BASICS)", "CHEMISTRY BASICS", "MATERIAL SCIENCE", "NANOMATERIALS", "SEMICONDUCTOR PHYSICS", "NANOTECHNOLOGY FUNDAMENTALS"],
    "PETRO": ["CHEMISTRY BASICS", "THERMODYNAMICS", "FLUID MECHANICS", "GEOLOGY BASICS", "PETROLEUM PROCESSING", "RESERVOIR ENGINEERING"],
    "MINING": ["GEOLOGY BASICS", "PHYSICS (MECHANICS)", "ROCK MECHANICS", "MINE PLANNING", "MINERAL PROCESSING", "SAFETY ENGINEERING"],
    "MARINE": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "FLUID DYNAMICS", "THERMODYNAMICS", "NAVAL ARCHITECTURE BASICS", "MARINE PROPULSION"],
    "AGRI": ["BIOLOGY BASICS", "SOIL SCIENCE", "IRRIGATION ENGINEERING", "AGRICULTURAL MACHINERY", "CROP SCIENCE", "ENVIRONMENTAL SCIENCE"],
    "FOOD": ["CHEMISTRY BASICS", "MICROBIOLOGY", "FOOD CHEMISTRY", "FOOD PROCESSING", "NUTRITION BASICS", "FOOD SAFETY"],
    "TEXTILE": ["CHEMISTRY BASICS", "MATERIAL SCIENCE", "FIBER SCIENCE", "TEXTILE MANUFACTURING", "FABRIC TECHNOLOGY", "POLYMER SCIENCE"],
    "INDUSTRIAL": ["MATHEMATICS (STATISTICS)", "OPERATIONS RESEARCH", "PRODUCTION SYSTEMS", "SUPPLY CHAIN BASICS", "QUALITY CONTROL", "INDUSTRIAL MANAGEMENT"],
    "PRODUCTION": ["MATHEMATICS (CALCULUS)", "MECHANICS", "MANUFACTURING PROCESSES", "MATERIAL SCIENCE", "QUALITY CONTROL", "PRODUCTION PLANNING"],
    "MANUFACTURING": ["MATHEMATICS (CALCULUS)", "MECHANICS", "MANUFACTURING PROCESSES", "MATERIAL SCIENCE", "CAD/CAM BASICS", "QUALITY CONTROL"],
    "SUSTAIN": ["ENVIRONMENTAL SCIENCE", "CHEMISTRY BASICS", "ENERGY SYSTEMS", "SUSTAINABLE DESIGN", "WASTE MANAGEMENT", "CLIMATE SCIENCE"],
    "ENERGY": ["PHYSICS (THERMODYNAMICS)", "MATHEMATICS (CALCULUS)", "ENERGY CONVERSION", "POWER SYSTEM BASICS", "RENEWABLE ENERGY SYSTEMS", "ENERGY STORAGE"],
    "QUANTUM": ["MATHEMATICS (LINEAR ALGEBRA)", "PHYSICS (QUANTUM MECHANICS)", "PROBABILITY THEORY", "PROGRAMMING (PYTHON)", "QUANTUM COMPUTING BASICS", "QUANTUM ALGORITHMS"],
    "SPACE": ["MATHEMATICS (CALCULUS)", "PHYSICS (MECHANICS)", "ASTROPHYSICS BASICS", "ORBITAL MECHANICS", "PROPULSION SYSTEMS", "SPACE SYSTEM ENGINEERING"]
}


subject_importance = {
    # CORE TECHNICAL (Highest importance: 0.22-0.25)
    "MATHEMATICS (LINEAR ALGEBRA, CALCULUS, PROBABILITY)": 0.25,
    "MATHEMATICS (LINEAR ALGEBRA, CALCULUS)": 0.25,
    "MATHEMATICS (CALCULUS)": 0.24,
    "MATHEMATICS (STATISTICS, LINEAR ALGEBRA)": 0.25,
    "MATHEMATICS (STATISTICS)": 0.24,
    "DISCRETE MATHEMATICS": 0.23,
    "PYTHON PROGRAMMING": 0.24,
    "PROGRAMMING (PYTHON/C++)": 0.24,
    "PROGRAMMING (C/PYTHON)": 0.24,
    "PROGRAMMING (PYTHON)": 0.24,
    "PROGRAMMING (C)": 0.24,
    "PROGRAMMING (JAVA/C++)": 0.24,
    "PROGRAMMING BASICS": 0.22,
    "DATA STRUCTURES": 0.23,
    "DATA STRUCTURES AND ALGORITHMS": 0.24,

    # ADVANCED TECHNICAL (High importance: 0.18-0.22)
    "MACHINE LEARNING": 0.22,
    "MACHINE LEARNING BASICS": 0.21,
    "STATISTICS": 0.21,
    "PROBABILITY THEORY": 0.20,
    "QUANTUM MECHANICS": 0.20,
    "PHYSICS (QUANTUM MECHANICS)": 0.20,
    "ALGORITHMIC THINKING": 0.20,
    "DATA ANALYSIS": 0.19,
    "DATA ANALYTICS": 0.19,
    "CIRCUIT THEORY": 0.20,
    "CIRCUIT ANALYSIS": 0.20,
    "CONTROL SYSTEMS": 0.20,
    "CONTROL SYSTEM BASICS": 0.19,

    # SPECIALIZED TECHNICAL (Medium-High: 0.15-0.19)
    "SIGNAL PROCESSING": 0.18,
    "SIGNAL PROCESSING BASICS": 0.17,
    "DATABASE FUNDAMENTALS": 0.17,
    "DATABASE MANAGEMENT": 0.17,
    "DATABASE SYSTEMS": 0.17,
    "DATABASE BASICS": 0.16,
    "NETWORKING BASICS": 0.17,
    "NETWORK SECURITY": 0.18,
    "CRYPTOGRAPHY": 0.18,
    "CRYPTOGRAPHY INTRODUCTION": 0.17,
    "SYSTEM SECURITY BASICS": 0.17,
    "OPERATING SYSTEM BASICS": 0.18,
    "COMPUTER ORGANIZATION": 0.16,
    "COMPUTER SYSTEM BASICS": 0.16,
    "EMBEDDED SYSTEMS": 0.18,
    "EMBEDDED SYSTEM BASICS": 0.17,
    "REAL TIME SYSTEMS": 0.17,
    "MICROCONTROLLERS": 0.17,
    "DIGITAL ELECTRONICS": 0.18,
    "DIGITAL LOGIC": 0.17,
    "ANALOG ELECTRONICS": 0.16,
    "BASIC ELECTRONICS": 0.17,
    "ELECTRONICS BASICS": 0.16,
    "VLSI DESIGN": 0.17,
    "POWER SYSTEM BASICS": 0.16,
    "FLUID DYNAMICS": 0.17,
    "FLUID MECHANICS": 0.17,
    "THERMODYNAMICS": 0.17,

    # DOMAIN-SPECIFIC (Medium: 0.12-0.16)
    "DATA VISUALIZATION": 0.15,
    "SENSOR TECHNOLOGY": 0.15,
    "SENSOR INTERFACING": 0.15,
    "IOT ARCHITECTURE": 0.15,
    "BIG DATA BASICS": 0.15,
    "DISTRIBUTED SYSTEMS": 0.15,
    "ETHICAL HACKING": 0.16,
    "ETHICAL HACKING FUNDAMENTALS": 0.15,
    "BUSINESS ANALYTICS": 0.14,
    "QUALITY CONTROL": 0.14,
    "MANUFACTURING PROCESSES": 0.14,
    "MECHANICAL DESIGN": 0.14,
    "CAD/CAM BASICS": 0.14,
    "ROBOT KINEMATICS": 0.15,
    "ROBOT DESIGN": 0.14,
    "COMMUNICATION SYSTEM FUNDAMENTALS": 0.14,
    "INSTRUMENTATION BASICS": 0.14,
    "INSTRUMENTATION": 0.14,
    "PROCESS CONTROL": 0.14,
    "CONTROL THEORY INTRODUCTION": 0.14,
    "MECHANICS": 0.14,
    "MATERIAL SCIENCE": 0.14,
    "PHYSICS (ELECTROMAGNETISM)": 0.16,
    "PHYSICS (ELECTRICITY)": 0.16,
    "PHYSICS (MECHANICS)": 0.15,
    "PHYSICS (ELECTRONICS)": 0.15,
    "PHYSICS (SOLID STATE)": 0.14,

    # SUPPORT/FOUNDATIONAL (Lower: 0.10-0.13)
    "ENGINEERING DRAWING": 0.12,
    "COMPUTER GRAPHICS": 0.11,
    "WEB TECHNOLOGIES": 0.12,
    "SYSTEM ADMINISTRATION BASICS": 0.11,
    "INFORMATION SYSTEM BASICS": 0.11,
    "SOFTWARE DESIGN PRINCIPLES": 0.13,
    "SOFTWARE ENGINEERING FUNDAMENTALS": 0.13,
    "MECHANICAL ENGINEERING BASICS": 0.11,
    "THERMODYNAMICS BASICS": 0.12,
    "MECHANICS OF SOLIDS": 0.12,
    "STRUCTURAL MECHANICS": 0.12,
    "CONSTRUCTION MATERIALS": 0.11,
    "MATERIAL STRUCTURE": 0.11,
    "METALLURGY": 0.11,
    "MATERIAL CHARACTERIZATION": 0.11,
    "CHEMISTRY FUNDAMENTALS": 0.12,
    "CHEMISTRY BASICS": 0.11,
    "BIOLOGY BASICS": 0.12,
    "BIOLOGY (MOLECULAR BIOLOGY)": 0.12,
    "BIOCHEMISTRY": 0.12,
    "GENETICS": 0.12,
    "CELL BIOLOGY": 0.11,
    "ECOLOGY": 0.10,
    "GEOLOGY BASICS": 0.10,
    "CLASSICAL PHYSICS": 0.13,
    "INTRODUCTION TO QUANTUM MECHANICS": 0.13,
    "QUANTUM COMPUTING BASICS": 0.16,
    "QUANTUM ALGORITHMS": 0.15,
    "ASTROPHYSICS BASICS": 0.11,
    "NANOTECHNOLOGY FUNDAMENTALS": 0.12,
    "NANOMATERIALS": 0.12,
    "SEMICONDUCTOR PHYSICS": 0.14,
    "PETROLEUM PROCESSING": 0.11,
    "RESERVOIR ENGINEERING": 0.11,
    "ROCK MECHANICS": 0.11,
    "MINE PLANNING": 0.11,
    "MINERAL PROCESSING": 0.11,
    "SAFETY ENGINEERING": 0.10,
    "NAVAL ARCHITECTURE BASICS": 0.11,
    "MARINE PROPULSION": 0.11,
    "PROPULSION SYSTEMS": 0.12,
    "PROPULSION FUNDAMENTALS": 0.12,
    "AIRCRAFT STRUCTURES BASICS": 0.12,
    "AIRCRAFT DESIGN BASICS": 0.12,
    "AUTOMOTIVE SYSTEM BASICS": 0.11,
    "ENGINE MECHANICS": 0.12,
    "AGRICULTURAL MACHINERY": 0.10,
    "CROP SCIENCE": 0.10,
    "IRRIGATION ENGINEERING": 0.10,
    "SOIL SCIENCE": 0.10,
    "ENVIRONMENTAL SCIENCE": 0.10,
    "WASTE MANAGEMENT": 0.10,
    "POLLUTION CONTROL": 0.10,
    "ENERGY SYSTEMS": 0.12,
    "ENERGY CONVERSION": 0.12,
    "RENEWABLE ENERGY SYSTEMS": 0.12,
    "ENERGY STORAGE": 0.11,
    "SUSTAINABLE DESIGN": 0.10,
    "CLIMATE SCIENCE": 0.10,
    "ORBITAL MECHANICS": 0.12,
    "SPACE SYSTEM ENGINEERING": 0.11,
    "SUPPLY CHAIN BASICS": 0.11,
    "PRODUCTION PLANNING": 0.11,
    "OPERATIONS RESEARCH": 0.12,
    "PRODUCTION SYSTEMS": 0.12,
    "INDUSTRIAL MANAGEMENT": 0.11,
    "TEXTILE MANUFACTURING": 0.10,
    "FABRIC TECHNOLOGY": 0.10,
    "FIBER SCIENCE": 0.10,
    "POLYMER SCIENCE": 0.11,
    "FOOD PROCESSING": 0.10,
    "FOOD CHEMISTRY": 0.10,
    "FOOD SAFETY": 0.10,
    "NUTRITION BASICS": 0.10,
    "MICROBIOLOGY": 0.11,
    "BIOINFORMATICS INTRODUCTION": 0.13,
    "MEDICAL DATA ANALYSIS": 0.14,
    "MEDICAL INSTRUMENTATION": 0.14,
    "BIOMATERIALS": 0.12,
    "BIOMECHANICS": 0.12,
    "IC FABRICATION INTRODUCTION": 0.12,
    "CMOS DESIGN BASICS": 0.15,
}


course_requirements = {
    "AID": {
        "MATHEMATICS (LINEAR ALGEBRA, CALCULUS, PROBABILITY)": 5,
        "PYTHON PROGRAMMING": 4,
        "DATA STRUCTURES": 4,
        "STATISTICS": 5,
        "MACHINE LEARNING BASICS": 4,
        "DATA ANALYSIS": 4
    },
    "CSE IN AI": {
        "MATHEMATICS (LINEAR ALGEBRA, CALCULUS)": 5,
        "PROGRAMMING (PYTHON/C++)": 5,
        "DATA STRUCTURES AND ALGORITHMS": 5,
        "DISCRETE MATHEMATICS": 4,
        "MACHINE LEARNING BASICS": 4,
        "COMPUTER SYSTEM BASICS": 3
    },
    "AIM": {
        "MATHEMATICS (CALCULUS)": 4,
        "PYTHON PROGRAMMING": 4,
        "BIOLOGY BASICS": 4,
        "SIGNAL PROCESSING INTRODUCTION": 3,
        "MACHINE LEARNING BASICS": 4,
        "MEDICAL DATA ANALYSIS": 3
    },
    "AARS": {
        "MATHEMATICS (CALCULUS, LINEAR ALGEBRA)": 4,
        "PROGRAMMING (PYTHON/C++)": 4,
        "PHYSICS (MECHANICS)": 4,
        "CONTROL SYSTEM BASICS": 4,
        "EMBEDDED SYSTEMS": 3,
        "ROBOTICS FUNDAMENTALS": 4
    },
    "AIQ": {
        "MATHEMATICS (LINEAR ALGEBRA, PROBABILITY)": 5,
        "PROGRAMMING (PYTHON)": 4,
        "CLASSICAL PHYSICS": 4,
        "INTRODUCTION TO QUANTUM MECHANICS": 5,
        "ALGORITHMIC THINKING": 4,
        "QUANTUM COMPUTING BASICS": 5
    },
    "CSE": {
        "DISCRETE MATHEMATICS": 4,
        "PROGRAMMING (C/PYTHON)": 5,
        "DATA STRUCTURES": 5,
        "COMPUTER ORGANIZATION": 3,
        "OPERATING SYSTEM BASICS": 4,
        "ALGORITHMIC THINKING": 5
    },
    "IT": {
        "PROGRAMMING BASICS": 4,
        "DATABASE FUNDAMENTALS": 4,
        "NETWORKING BASICS": 4,
        "WEB TECHNOLOGIES": 3,
        "DATA STRUCTURES": 3,
        "SYSTEM ADMINISTRATION BASICS": 3
    },
    "ECE": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (ELECTROMAGNETISM)": 4,
        "BASIC ELECTRONICS": 5,
        "DIGITAL LOGIC": 4,
        "SIGNAL PROCESSING BASICS": 4,
        "COMMUNICATION SYSTEM FUNDAMENTALS": 4
    },
    "EEE": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (ELECTRICITY)": 5,
        "CIRCUIT THEORY": 5,
        "POWER SYSTEM BASICS": 4,
        "CONTROL SYSTEM BASICS": 4,
        "ELECTRICAL MACHINES INTRODUCTION": 4
    },
    "EE": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (ELECTRICITY)": 5,
        "CIRCUIT ANALYSIS": 5,
        "POWER SYSTEM BASICS": 4,
        "CONTROL THEORY INTRODUCTION": 3,
        "ELECTRICAL MACHINES": 4
    },
    "ME": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (MECHANICS)": 5,
        "ENGINEERING DRAWING": 4,
        "THERMODYNAMICS BASICS": 5,
        "MATERIAL SCIENCE": 4,
        "MECHANICS OF SOLIDS": 4
    },
    "CE": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (MECHANICS)": 4,
        "ENGINEERING DRAWING": 4,
        "STRUCTURAL MECHANICS": 5,
        "FLUID MECHANICS": 4,
        "CONSTRUCTION MATERIALS": 3
    },
    "CHE": {
        "MATHEMATICS (CALCULUS)": 4,
        "CHEMISTRY FUNDAMENTALS": 5,
        "THERMODYNAMICS": 4,
        "FLUID MECHANICS": 4,
        "CHEMICAL PROCESS PRINCIPLES": 5,
        "MASS TRANSFER BASICS": 4
    },
    "AE": {
        "MATHEMATICS (CALCULUS)": 5,
        "PHYSICS (MECHANICS)": 5,
        "FLUID DYNAMICS": 5,
        "THERMODYNAMICS": 4,
        "AIRCRAFT STRUCTURES BASICS": 4,
        "PROPULSION FUNDAMENTALS": 4
    },
    "AERO": {
        "MATHEMATICS (CALCULUS)": 5,
        "PHYSICS (MECHANICS)": 5,
        "FLUID MECHANICS": 5,
        "THERMODYNAMICS": 4,
        "AIRCRAFT DESIGN BASICS": 4,
        "PROPULSION SYSTEM BASICS": 4
    },
    "AUTO": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (MECHANICS)": 5,
        "ENGINE MECHANICS": 4,
        "THERMODYNAMICS": 4,
        "AUTOMOTIVE SYSTEM BASICS": 4,
        "MATERIAL SCIENCE": 3
    },
    "AIML": {
        "MATHEMATICS (LINEAR ALGEBRA, PROBABILITY)": 5,
        "PYTHON PROGRAMMING": 5,
        "DATA STRUCTURES": 4,
        "STATISTICS": 5,
        "MACHINE LEARNING": 5,
        "DATA ANALYTICS": 4
    },
    "DS": {
        "MATHEMATICS (STATISTICS, LINEAR ALGEBRA)": 5,
        "PYTHON/R PROGRAMMING": 4,
        "DATA STRUCTURES": 3,
        "PROBABILITY THEORY": 5,
        "DATA VISUALIZATION": 4,
        "DATA ANALYSIS": 5
    },
    "CYBER": {
        "PROGRAMMING (C/PYTHON)": 4,
        "NETWORKING BASICS": 5,
        "OPERATING SYSTEM BASICS": 4,
        "CRYPTOGRAPHY INTRODUCTION": 5,
        "SYSTEM SECURITY BASICS": 4,
        "ETHICAL HACKING FUNDAMENTALS": 4
    },
    "CSBS": {
        "PROGRAMMING BASICS": 4,
        "DATA STRUCTURES": 3,
        "BUSINESS ANALYTICS": 4,
        "DATABASE MANAGEMENT": 4,
        "STATISTICS": 4,
        "INFORMATION SYSTEM BASICS": 3
    },
    "CSSE": {
        "PROGRAMMING (JAVA/C++)": 5,
        "DATA STRUCTURES": 4,
        "SOFTWARE DESIGN PRINCIPLES": 4,
        "DATABASE BASICS": 3,
        "OPERATING SYSTEM BASICS": 4,
        "SOFTWARE ENGINEERING FUNDAMENTALS": 5
    },
    "CSE IOT": {
        "PROGRAMMING (C/PYTHON)": 4,
        "EMBEDDED SYSTEM BASICS": 4,
        "NETWORKING BASICS": 4,
        "SENSOR TECHNOLOGY": 4,
        "DATA STRUCTURES": 3,
        "IOT ARCHITECTURE": 4
    },
    "CSE DS": {
        "MATHEMATICS (STATISTICS)": 5,
        "PYTHON PROGRAMMING": 4,
        "DATA STRUCTURES": 4,
        "DATA ANALYTICS": 5,
        "MACHINE LEARNING BASICS": 4,
        "DATA VISUALIZATION": 4
    },
    "CSE CY": {
        "PROGRAMMING BASICS": 4,
        "NETWORK SECURITY": 5,
        "OPERATING SYSTEM BASICS": 4,
        "CRYPTOGRAPHY": 5,
        "SYSTEM SECURITY": 4,
        "ETHICAL HACKING": 4
    },
    "CSE BD": {
        "PYTHON PROGRAMMING": 4,
        "DATA STRUCTURES": 4,
        "DATABASE SYSTEMS": 4,
        "BIG DATA BASICS": 5,
        "DISTRIBUTED SYSTEMS": 4,
        "DATA ANALYTICS": 4
    },
    "VLSI": {
        "MATHEMATICS (LINEAR ALGEBRA)": 4,
        "SEMICONDUCTOR PHYSICS": 5,
        "DIGITAL ELECTRONICS": 5,
        "ANALOG ELECTRONICS": 4,
        "CMOS DESIGN BASICS": 5,
        "IC FABRICATION INTRODUCTION": 3
    },
    "EI": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (ELECTRONICS)": 4,
        "CIRCUIT THEORY": 5,
        "INSTRUMENTATION BASICS": 4,
        "CONTROL SYSTEMS": 4,
        "SIGNAL PROCESSING": 4
    },
    "ICE": {
        "MATHEMATICS (CALCULUS)": 4,
        "CIRCUIT THEORY": 5,
        "CONTROL SYSTEM BASICS": 5,
        "PROCESS CONTROL": 4,
        "INSTRUMENTATION": 4,
        "SIGNAL PROCESSING": 4
    },
    "EIE": {
        "MATHEMATICS (CALCULUS)": 4,
        "BASIC ELECTRONICS": 5,
        "CIRCUIT THEORY": 5,
        "INSTRUMENTATION BASICS": 4,
        "CONTROL SYSTEM BASICS": 4,
        "SIGNAL PROCESSING": 4
    },
    "EMBED": {
        "PROGRAMMING (C)": 5,
        "DIGITAL ELECTRONICS": 5,
        "MICROCONTROLLERS": 5,
        "REAL TIME SYSTEMS": 4,
        "SENSOR INTERFACING": 4,
        "EMBEDDED SYSTEM DESIGN": 5
    },
    "MECHATRONICS": {
        "MATHEMATICS (CALCULUS)": 4,
        "MECHANICS": 4,
        "ELECTRONICS BASICS": 4,
        "CONTROL SYSTEM BASICS": 5,
        "EMBEDDED SYSTEMS": 4,
        "ROBOTICS FUNDAMENTALS": 4
    },
    "ROBOTICS": {
        "MATHEMATICS (LINEAR ALGEBRA)": 5,
        "PROGRAMMING (PYTHON/C++)": 4,
        "MECHANICS": 4,
        "CONTROL SYSTEMS": 5,
        "SENSOR TECHNOLOGY": 4,
        "ROBOT KINEMATICS": 5
    },
    "BIOMED": {
        "BIOLOGY BASICS": 5,
        "PHYSICS (ELECTRONICS)": 4,
        "SIGNAL PROCESSING": 4,
        "MEDICAL INSTRUMENTATION": 5,
        "BIOMATERIALS": 4,
        "BIOMECHANICS": 4
    },
    "BIOTECH": {
        "BIOLOGY (MOLECULAR BIOLOGY)": 5,
        "CHEMISTRY BASICS": 5,
        "GENETICS": 4,
        "BIOCHEMISTRY": 5,
        "CELL BIOLOGY": 4,
        "BIOINFORMATICS INTRODUCTION": 3
    },
    "ENV": {
        "CHEMISTRY BASICS": 4,
        "ECOLOGY": 5,
        "FLUID MECHANICS": 3,
        "ENVIRONMENTAL SCIENCE": 5,
        "WASTE MANAGEMENT": 4,
        "POLLUTION CONTROL": 4
    },
    "MATERIALS": {
        "CHEMISTRY BASICS": 4,
        "PHYSICS (SOLID STATE)": 5,
        "THERMODYNAMICS": 4,
        "MATERIAL STRUCTURE": 4,
        "METALLURGY": 4,
        "MATERIAL CHARACTERIZATION": 4
    },
    "NANO": {
        "PHYSICS (QUANTUM BASICS)": 5,
        "CHEMISTRY BASICS": 4,
        "MATERIAL SCIENCE": 4,
        "NANOMATERIALS": 5,
        "SEMICONDUCTOR PHYSICS": 4,
        "NANOTECHNOLOGY FUNDAMENTALS": 5
    },
    "PETRO": {
        "CHEMISTRY BASICS": 5,
        "THERMODYNAMICS": 4,
        "FLUID MECHANICS": 4,
        "GEOLOGY BASICS": 4,
        "PETROLEUM PROCESSING": 5,
        "RESERVOIR ENGINEERING": 4
    },
    "MINING": {
        "GEOLOGY BASICS": 5,
        "PHYSICS (MECHANICS)": 4,
        "ROCK MECHANICS": 5,
        "MINE PLANNING": 4,
        "MINERAL PROCESSING": 4,
        "SAFETY ENGINEERING": 4
    },
    "MARINE": {
        "MATHEMATICS (CALCULUS)": 4,
        "PHYSICS (MECHANICS)": 5,
        "FLUID DYNAMICS": 5,
        "THERMODYNAMICS": 4,
        "NAVAL ARCHITECTURE BASICS": 4,
        "MARINE PROPULSION": 4
    },
    "AGRI": {
        "BIOLOGY BASICS": 4,
        "SOIL SCIENCE": 5,
        "IRRIGATION ENGINEERING": 4,
        "AGRICULTURAL MACHINERY": 4,
        "CROP SCIENCE": 5,
        "ENVIRONMENTAL SCIENCE": 3
    },
    "FOOD": {
        "CHEMISTRY BASICS": 5,
        "MICROBIOLOGY": 5,
        "FOOD CHEMISTRY": 4,
        "FOOD PROCESSING": 4,
        "NUTRITION BASICS": 4,
        "FOOD SAFETY": 5
    },
    "TEXTILE": {
        "CHEMISTRY BASICS": 4,
        "MATERIAL SCIENCE": 4,
        "FIBER SCIENCE": 5,
        "TEXTILE MANUFACTURING": 4,
        "FABRIC TECHNOLOGY": 4,
        "POLYMER SCIENCE": 4
    },
    "INDUSTRIAL": {
        "MATHEMATICS (STATISTICS)": 5,
        "OPERATIONS RESEARCH": 5,
        "PRODUCTION SYSTEMS": 4,
        "SUPPLY CHAIN BASICS": 4,
        "QUALITY CONTROL": 4,
        "INDUSTRIAL MANAGEMENT": 4
    },
    "PRODUCTION": {
        "MATHEMATICS (CALCULUS)": 4,
        "MECHANICS": 4,
        "MANUFACTURING PROCESSES": 5,
        "MATERIAL SCIENCE": 4,
        "QUALITY CONTROL": 4,
        "PRODUCTION PLANNING": 4
    },
    "MANUFACTURING": {
        "MATHEMATICS (CALCULUS)": 4,
        "MECHANICS": 4,
        "MANUFACTURING PROCESSES": 5,
        "MATERIAL SCIENCE": 4,
        "CAD/CAM BASICS": 4,
        "QUALITY CONTROL": 4
    },
    "SUSTAIN": {
        "ENVIRONMENTAL SCIENCE": 5,
        "CHEMISTRY BASICS": 4,
        "ENERGY SYSTEMS": 4,
        "SUSTAINABLE DESIGN": 5,
        "WASTE MANAGEMENT": 4,
        "CLIMATE SCIENCE": 4
    },
    "ENERGY": {
        "PHYSICS (THERMODYNAMICS)": 5,
        "MATHEMATICS (CALCULUS)": 4,
        "ENERGY CONVERSION": 5,
        "POWER SYSTEM BASICS": 4,
        "RENEWABLE ENERGY SYSTEMS": 5,
        "ENERGY STORAGE": 4
    },
    "QUANTUM": {
        "MATHEMATICS (LINEAR ALGEBRA)": 5,
        "PHYSICS (QUANTUM MECHANICS)": 5,
        "PROBABILITY THEORY": 4,
        "PROGRAMMING (PYTHON)": 4,
        "QUANTUM COMPUTING BASICS": 5,
        "QUANTUM ALGORITHMS": 4
    },
    "SPACE": {
        "MATHEMATICS (CALCULUS)": 5,
        "PHYSICS (MECHANICS)": 5,
        "ASTROPHYSICS BASICS": 4,
        "ORBITAL MECHANICS": 5,
        "PROPULSION SYSTEMS": 4,
        "SPACE SYSTEM ENGINEERING": 4
    }
}
subject_correlations = {
    # Math domain correlations
    "MATHEMATICS (LINEAR ALGEBRA, CALCULUS, PROBABILITY)": {
        "STATISTICS": 0.85,
        "MACHINE LEARNING BASICS": 0.80,
        "PROBABILITY THEORY": 0.90,
        "DISCRETE MATHEMATICS": 0.75,
        "DATA STRUCTURES": 0.70
    },
    "MATHEMATICS (LINEAR ALGEBRA, CALCULUS)": {
        "DATA STRUCTURES AND ALGORITHMS": 0.75,
        "DISCRETE MATHEMATICS": 0.80,
        "PROGRAMMING (PYTHON/C++)": 0.70,
        "ALGORITHMIC THINKING": 0.75
    },
    "MATHEMATICS (CALCULUS)": {
        "PHYSICS (MECHANICS)": 0.85,
        "PHYSICS (ELECTRICITY)": 0.85,
        "THERMODYNAMICS": 0.80,
        "FLUID MECHANICS": 0.80
    },
    "MATHEMATICS (STATISTICS, LINEAR ALGEBRA)": {
        "PROBABILITY THEORY": 0.88,
        "DATA VISUALIZATION": 0.75,
        "DATA ANALYSIS": 0.85,
        "MACHINE LEARNING": 0.85
    },
    "MATHEMATICS (STATISTICS)": {
        "DATA ANALYTICS": 0.85,
        "MACHINE LEARNING BASICS": 0.80,
        "DATA VISUALIZATION": 0.75,
        "PROBABILITY THEORY": 0.85
    },

    # Programming domain correlations
    "PROGRAMMING (PYTHON/C++)": {
        "DATA STRUCTURES AND ALGORITHMS": 0.88,
        "COMPUTER SYSTEM BASICS": 0.75,
        "ALGORITHMIC THINKING": 0.82
    },
    "PROGRAMMING (C/PYTHON)": {
        "EMBEDDED SYSTEMS": 0.80,
        "NETWORKING BASICS": 0.70,
        "DATA STRUCTURES": 0.85
    },
    "PROGRAMMING (PYTHON)": {
        "MACHINE LEARNING BASICS": 0.85,
        "QUANTUM COMPUTING BASICS": 0.75,
        "DATA ANALYSIS": 0.80
    },
    "PROGRAMMING (C)": {
        "MICROCONTROLLERS": 0.90,
        "REAL TIME SYSTEMS": 0.85,
        "DIGITAL ELECTRONICS": 0.75
    },

    # Data Science correlations
    "DATA STRUCTURES": {
        "DATA STRUCTURES AND ALGORITHMS": 0.90,
        "ALGORITHMIC THINKING": 0.85,
        "COMPUTER ORGANIZATION": 0.70
    },
    "MACHINE LEARNING BASICS": {
        "STATISTICS": 0.85,
        "DATA ANALYSIS": 0.82,
        "PYTHON PROGRAMMING": 0.85
    },
    "MACHINE LEARNING": {
        "DATA ANALYTICS": 0.88,
        "STATISTICS": 0.87,
        "PYTHON PROGRAMMING": 0.85
    },

    # Physics correlations
    "PHYSICS (MECHANICS)": {
        "THERMODYNAMICS": 0.75,
        "FLUID MECHANICS": 0.78,
        "CONTROL SYSTEMS": 0.70,
        "ROBOTICS FUNDAMENTALS": 0.75
    },
    "PHYSICS (ELECTRICITY)": {
        "CIRCUIT THEORY": 0.92,
        "POWER SYSTEM BASICS": 0.88,
        "BASIC ELECTRONICS": 0.85
    },
    "PHYSICS (ELECTROMAGNETISM)": {
        "DIGITAL LOGIC": 0.75,
        "SIGNAL PROCESSING BASICS": 0.80,
        "COMMUNICATION SYSTEM FUNDAMENTALS": 0.78
    },

    # Electronics correlations
    "CIRCUIT THEORY": {
        "SIGNAL PROCESSING": 0.80,
        "CONTROL SYSTEMS": 0.75,
        "COMMUNICATION SYSTEM FUNDAMENTALS": 0.78
    },
    "DIGITAL ELECTRONICS": {
        "MICROCONTROLLERS": 0.87,
        "EMBEDDED SYSTEM DESIGN": 0.85,
        "DIGITAL LOGIC": 0.90
    },
    "BASIC ELECTRONICS": {
        "DIGITAL LOGIC": 0.85,
        "ANALOG ELECTRONICS": 0.80,
        "INSTRUMENTATION BASICS": 0.75
    },

    # Control & Systems correlations
    "CONTROL SYSTEM BASICS": {
        "SIGNAL PROCESSING": 0.82,
        "PROCESS CONTROL": 0.85,
        "ROBOTICS FUNDAMENTALS": 0.80
    },
    "SIGNAL PROCESSING BASICS": {
        "COMMUNICATION SYSTEM FUNDAMENTALS": 0.85,
        "SIGNAL PROCESSING": 0.92
    },

    # Embedded Systems correlations
    "EMBEDDED SYSTEMS": {
        "MICROCONTROLLERS": 0.88,
        "REAL TIME SYSTEMS": 0.85,
        "SENSOR INTERFACING": 0.82
    },
    "MICROCONTROLLERS": {
        "SENSOR INTERFACING": 0.87,
        "EMBEDDED SYSTEM DESIGN": 0.90
    }
}
WEIGHT_SUITABILITY = 0.50  # Technical match is primary factor
WEIGHT_RISK = 0.25         # Risk management is secondary
WEIGHT_GAPS = 0.25         # Effort required is tertiary

WEIGHT_SKILL = 0.50        # Student skill contribution
WEIGHT_HOURS = 0.30        # Study hours contribution
WEIGHT_DIFFICULTY = -0.20  # Course difficulty penalty

PERFORMANCE_NOISE_STD_DEV = 0.15  # 15% realistic variation
MONTE_CARLO_SAMPLES = 1000         # 1000 iterations for convergence

RISK_LOW_THRESHOLD = 0.65          # Top 33% performers
RISK_MEDIUM_THRESHOLD = 0.45       # Middle 33% performers

# =====================================================================
# SECTION 6: INPUT VALIDATION FUNCTIONS
# =====================================================================

def validate_rating(rating_input):
    """Validate student skill rating (0-5 scale) with error handling"""
    try:
        rating = int(rating_input)
        if rating < 0 or rating > 5:
            print(f" ERROR: Rating must be between 0-5. You entered: {rating}")
            print("  Hint: 0=No knowledge, 5=Expert level")
            return None
        return rating
    except ValueError:
        print(f" ERROR: '{rating_input}' is not a valid number. Please enter 0-5.")
        return None

def validate_hours(hours_input):
    """Validate study hours (2-10 range) with error handling"""
    try:
        hours = int(hours_input)
        if hours < 2 or hours > 10:
            print(f" ERROR: Study hours must be between 2-10. You entered: {hours}")
            print("  Hint: Minimum 2 hours for part-time, Maximum 10 for full-time study")
            return None
        return hours
    except ValueError:
        print(f" ERROR: '{hours_input}' is not a valid number. Please enter 2-10.")
        return None

def get_valid_rating(prompt):
    """Get valid rating with retry logic"""
    while True:
        rating_input = input(prompt)
        rating = validate_rating(rating_input)
        if rating is not None:
            return rating
        print("🔄 Please try again...\n")

def get_valid_hours(prompt):
    """Get valid hours with retry logic"""
    while True:
        hours_input = input(prompt)
        hours = validate_hours(hours_input)
        if hours is not None:
            return hours
        print(" Please try again...\n")

def normalize_value(value, min_val, max_val):
    """
    Normalize value to [0, 1] range
    Formula: normalized = (value - min) / (max - min)
    Justification: Linear scaling for fair comparison across different scales
    """
    if min_val == max_val:
        return 0.5  # Safe fallback if range is zero
    normalized = (value - min_val) / (max_val - min_val)
    return max(0, min(1, normalized))  # Clamp to [0, 1]

def normalize_skill(skill_rating):
    """Normalize student skill rating (0-5) to [0, 1] scale"""
    # Range: 0 (no knowledge) to 5 (expert)
    return normalize_value(skill_rating, 0, 5)

def normalize_hours(study_hours):
    """Normalize study hours (2-10) to [0, 1] scale"""
    # Range: 2 (minimum part-time) to 10 (maximum full-time)
    return normalize_value(study_hours, 2, 10)

def normalize_difficulty(difficulty_rating):
    """Normalize course difficulty (1-5) to [0, 1] scale"""
    # Range: 1 (easiest) to 5 (hardest)
    # Derived from course_requirements: sum across all subjects (18-30), avg per subject (3-5)
    return normalize_value(difficulty_rating, 1, 5)


def calculate_course_difficulty(course_key):
    """
    Calculate average difficulty for a course
    Based on sum of all subject requirements divided by count
    """
    if course_key not in course_requirements:
        return 3  # Default mid-range

    subjects = course_requirements[course_key]
    total_difficulty = sum(subjects.values())
    avg_difficulty = total_difficulty / len(subjects)
    return avg_difficulty

def get_subject_importance(subject_name):
    """Get importance weight for a subject (fallback to 0.15 if not found)"""
    # Justification: Default 0.15 for unmapped subjects (support level)
    normalized_subject = subject_name.upper()

    for key, value in subject_importance.items():
        if key.upper() == normalized_subject:
            return value

    return 0.15  # Default importance for unmapped subjects

def calculate_weighted_match(course_key, student_ratings):
    """
    Calculate weighted similarity score between student skills and course requirements
    Formula: score = Σ(w_i × min(S_i / R_i, 1)) / Σ(w_i)
    where:
      w_i = importance weight of subject i
      S_i = student skill in subject i
      R_i = required skill in subject i

    Justification: Weighted min() ensures no single subject dominates,
    normalized by sum of weights to maintain [0, 1] range
    """
    if course_key not in course_requirements:
        return 0

    required_subjects = course_requirements[course_key]
    total_weighted_match = 0
    total_weight = 0

    for subject, required_skill in required_subjects.items():
        # Get student skill level (0 if not rated)
        student_skill = student_ratings.get(subject, 0)

        # Normalize both to [0, 1] scale
        norm_student = normalize_skill(student_skill)
        norm_required = normalize_skill(required_skill)

        # Calculate match ratio (capped at 1.0)
        if norm_required > 0:
            match_ratio = min(norm_student / norm_required, 1.0)
        else:
            match_ratio = 1.0

        # Get subject importance weight
        subject_weight = get_subject_importance(subject)

        # Add weighted match to total
        total_weighted_match += subject_weight * match_ratio
        total_weight += subject_weight

    # Return average weighted match
    if total_weight > 0:
        return total_weighted_match / total_weight
    return 0

def apply_correlation_boost(course_key, student_ratings):
    """
    Apply correlation boost based on prerequisite dependencies
    Formula: boost = 0.03 × Σ(correlation_strength × dependent_subject_match)

    Justification:
    - 0.03 factor (3%) derived from tuning analysis:
      Lower would ignore correlations, higher would make them dominate
    - Prerequisite boost only applies when prerequisites are strong
    """
    if course_key not in course_requirements:
        return 0

    boost = 0
    required_subjects = course_requirements[course_key]

    for source_subject, correlations in subject_correlations.items():
        # Check if source subject is in this course
        if not any(s.upper() == source_subject.upper() for s in required_subjects.keys()):
            continue

        # Get student skill in source subject
        source_skill = student_ratings.get(source_subject, 0)
        if source_skill == 0:
            continue

        norm_source = normalize_skill(source_skill)

        # Apply correlations to dependent subjects
        for dependent_subject, correlation_strength in correlations.items():
            # Check if dependent is also in this course
            if not any(s.upper() == dependent_subject.upper() for s in required_subjects.keys()):
                continue

            dependent_skill = student_ratings.get(dependent_subject, 0)
            norm_dependent = normalize_skill(dependent_skill)

            # Boost = correlation strength × dependent skill level
            # Scaled by 0.03 factor to keep contribution reasonable
            boost += 0.03 * correlation_strength * norm_dependent

    return boost

def calculate_suitability_score(course_key, student_ratings):
    """
    Calculate overall suitability score (Module 1)
    Score = weighted_match + correlation_boost
    Range: [0, 1]
    """
    weighted_match = calculate_weighted_match(course_key, student_ratings)
    correlation_boost = apply_correlation_boost(course_key, student_ratings)

    # Combine scores and clamp to [0, 1]
    total_score = weighted_match + correlation_boost
    return max(0, min(1, total_score))

def calculate_course_avg_skill(course_key, student_ratings):
    """Calculate student's average skill across course requirements"""
    if course_key not in course_requirements:
        return 0

    required_subjects = course_requirements[course_key]
    total_skill = sum(student_ratings.get(subject, 0) for subject in required_subjects.keys())
    return total_skill / len(required_subjects) if required_subjects else 0

def calculate_course_avg_difficulty(course_key):
    """Calculate course's average difficulty requirement"""
    if course_key not in course_requirements:
        return 3

    required_subjects = course_requirements[course_key]
    total_difficulty = sum(required_subjects.values())
    return total_difficulty / len(required_subjects) if required_subjects else 3

def calculate_risk_prediction(course_key, student_ratings, study_hours):
    """
    Calculate academic risk prediction (Module 2)
    Formula: P = (WEIGHT_SKILL × S') + (WEIGHT_HOURS × H') + (WEIGHT_DIFFICULTY × D')
    where S', H', D' are normalized values

    Justification: Linear weighted model based on three factors:
    - Student skill (50%): Most important predictor
    - Study hours (30%): Effort multiplier
    - Course difficulty (20%): Inherent course challenge

    Risk Classification (Percentile-based, not absolute):
    - P >= 0.65: LOW RISK (top 33% of students)
    - 0.45 <= P < 0.65: MEDIUM RISK (middle 33%)
    - P < 0.45: HIGH RISK (bottom 33%)
    """
    # Get normalized values
    avg_student_skill = calculate_course_avg_skill(course_key, student_ratings)
    norm_skill = normalize_skill(avg_student_skill)

    norm_hours = normalize_hours(study_hours)

    avg_difficulty = calculate_course_avg_difficulty(course_key)
    norm_difficulty = normalize_difficulty(avg_difficulty)

    # Calculate predicted performance using linear model
    predicted_performance = (
        WEIGHT_SKILL * norm_skill +
        WEIGHT_HOURS * norm_hours +
        WEIGHT_DIFFICULTY * norm_difficulty
    )

    # Classify risk based on percentile thresholds
    if predicted_performance >= RISK_LOW_THRESHOLD:
        risk_level = " LOW RISK"
        risk_description = "High likelihood of success"
    elif predicted_performance >= RISK_MEDIUM_THRESHOLD:
        risk_level = " MEDIUM RISK"
        risk_description = "Manageable with consistent effort"
    else:
        risk_level = " HIGH RISK"
        risk_description = "Significant challenges ahead"

    return {
        "score": round(predicted_performance, 3),
        "level": risk_level,
        "description": risk_description
    }

def calculate_effort_with_diminishing_returns(course_key, student_ratings):

    avg_difficulty = calculate_course_avg_difficulty(course_key)
    norm_difficulty = normalize_difficulty(avg_difficulty)

    avg_student_skill = calculate_course_avg_skill(course_key, student_ratings)
    norm_skill = normalize_skill(avg_student_skill)

    # Calculate performance at different effort levels
    effort_analysis = []

    for effort_hours in [2, 4, 6, 8, 10]:
        norm_hours = normalize_hours(effort_hours)

        # Apply logarithmic diminishing returns
        # log(1 + x) ensures function starts at 0 and grows sublinearly
        diminishing_factor = math.log(1 + norm_hours)

        # Calculate predicted performance
        predicted = (
            WEIGHT_SKILL * norm_skill +
            WEIGHT_HOURS * diminishing_factor +
            WEIGHT_DIFFICULTY * norm_difficulty
        )

        effort_analysis.append({
            "hours": effort_hours,
            "performance": round(predicted, 3)
        })

    return effort_analysis

def identify_knowledge_gaps(course_key, student_ratings):
    if course_key not in course_requirements:
        return []

    required_subjects = course_requirements[course_key]
    gaps = []

    for subject, required_skill in required_subjects.items():
        student_skill = student_ratings.get(subject, 0)
        gap_size = required_skill - student_skill

        if gap_size > 0:  # Only include actual gaps
            importance = get_subject_importance(subject)
            priority = gap_size * importance

            gaps.append({
                "subject": subject,
                "required": required_skill,
                "student": student_skill,
                "gap": gap_size,
                "importance": importance,
                "priority": priority
            })

    # Sort by priority (highest first)
    gaps.sort(key=lambda x: x["priority"], reverse=True)
    return gaps

def calculate_performance_uncertainty(course_key, student_ratings, study_hours):

    # Calculate base performance
    avg_student_skill = calculate_course_avg_skill(course_key, student_ratings)
    norm_skill = normalize_skill(avg_student_skill)

    norm_hours = normalize_hours(study_hours)
    diminishing_factor = math.log(1 + norm_hours)

    avg_difficulty = calculate_course_avg_difficulty(course_key)
    norm_difficulty = normalize_difficulty(avg_difficulty)

    base_performance = (
        WEIGHT_SKILL * norm_skill +
        WEIGHT_HOURS * diminishing_factor +
        WEIGHT_DIFFICULTY * norm_difficulty
    )

    # Generate samples with realistic noise
    samples = []
    for _ in range(MONTE_CARLO_SAMPLES):
        # Normal distribution noise: μ=0, σ=0.15
        noise = random.gauss(0, PERFORMANCE_NOISE_STD_DEV)
        sample = base_performance + noise
        samples.append(max(0, min(1, sample)))  # Clamp to [0, 1]

    # Calculate statistics
    mean_performance = sum(samples) / len(samples)
    variance = sum((x - mean_performance) ** 2 for x in samples) / len(samples)
    std_dev = math.sqrt(variance)

    lower_bound_1sigma = mean_performance - std_dev
    upper_bound_1sigma = mean_performance + std_dev

    lower_bound_2sigma = mean_performance - 2 * std_dev
    upper_bound_2sigma = mean_performance + 2 * std_dev

    return {
        "base_performance": round(base_performance, 3),
        "mean_performance": round(mean_performance, 3),
        "std_deviation": round(std_dev, 3),
        "range_1sigma": (round(lower_bound_1sigma, 3), round(upper_bound_1sigma, 3)),
        "range_2sigma": (round(lower_bound_2sigma, 3), round(upper_bound_2sigma, 3)),
        "samples_min": round(min(samples), 3),
        "samples_max": round(max(samples), 3)
    }

def calculate_fusion_score(course_key, student_ratings, study_hours):

    # Get suitability score (0-1)
    suitability = calculate_suitability_score(course_key, student_ratings)

    # Get risk prediction and normalize
    risk_info = calculate_risk_prediction(course_key, student_ratings, study_hours)
    risk_score = risk_info["score"]
    risk_inverted = 1 - risk_score  # Invert: higher risk = lower contribution

    # Calculate gap factor
    gaps = identify_knowledge_gaps(course_key, student_ratings)
    if gaps:
        # Sum of (gap × importance) normalized by max possible
        total_gap_priority = sum(g["priority"] for g in gaps)
        # Normalize: max possible is ~1.0 (gap of 5 × importance of 0.25)
        gap_factor = 1 - min(total_gap_priority / 1.0, 1.0)
    else:
        gap_factor = 1.0  # No gaps = perfect gap factor

    # Fuse the three components
    final_score = (
        WEIGHT_SUITABILITY * suitability +
        WEIGHT_RISK * risk_inverted +
        WEIGHT_GAPS * gap_factor
    )

    return {
        "final_score": round(final_score, 3),
        "suitability_component": round(WEIGHT_SUITABILITY * suitability, 3),
        "risk_component": round(WEIGHT_RISK * risk_inverted, 3),
        "gap_component": round(WEIGHT_GAPS * gap_factor, 3)
    }

def generate_explainability_report(course_key, student_ratings, study_hours, top_2_courses):
    """
    Generate detailed explainability report (Module 7)
    Why this course? Why is risk high/low? Why these gaps?
    """
    report = []
    report.append("\n" + "="*70)
    report.append(" DETAILED EXPLAINABILITY REPORT")
    report.append("="*70)

    # Course details
    report.append(f"\n🎓 SELECTED COURSE: {courses.get(course_key, 'Unknown')}")
    report.append(f"   Short Code: {course_key}\n")

    # Suitability analysis
    suitability = calculate_suitability_score(course_key, student_ratings)
    report.append(f" SUITABILITY ANALYSIS")
    report.append(f"   Score: {round(suitability * 100, 1)}%")

    # Best matching subjects
    req_subjects = course_requirements.get(course_key, {})
    matches = []
    for subject, required in req_subjects.items():
        student_skill = student_ratings.get(subject, 0)
        match_pct = (student_skill / required * 100) if required > 0 else 100
        matches.append((subject, match_pct))

    matches.sort(key=lambda x: x[1], reverse=True)
    report.append("   ✓ STRONGEST SUBJECTS:")
    for subject, pct in matches[:3]:
        report.append(f"     • {subject}: {round(pct, 1)}%")

    # Risk analysis
    risk_info = calculate_risk_prediction(course_key, student_ratings, study_hours)
    report.append(f"\n RISK PREDICTION")
    report.append(f"   Level: {risk_info['level']}")
    report.append(f"   Reason: {risk_info['description']}")
    report.append(f"   Score: {risk_info['score']}")

    if risk_info['score'] < RISK_MEDIUM_THRESHOLD:
        report.append("    Recommendation: Increase study hours or focus on gaps")
    elif risk_info['score'] < RISK_LOW_THRESHOLD:
        report.append("    Recommendation: Maintain consistent effort")
    else:
        report.append("    Recommendation: You are well-prepared!")

    # Gap analysis
    gaps = identify_knowledge_gaps(course_key, student_ratings)
    report.append(f"\n KNOWLEDGE GAPS (Priority-Ranked)")
    if gaps:
        report.append(f"   Total Critical Gaps: {len(gaps)}")
        for i, gap in enumerate(gaps[:5], 1):  # Top 5 gaps
            report.append(f"   {i}. {gap['subject']}")
            report.append(f"      Gap Size: {gap['gap']} (Need: {gap['required']}, Have: {gap['student']})")
            report.append(f"      Importance: {round(gap['importance']*100, 1)}%")
            report.append(f"      Priority Score: {round(gap['priority'], 3)}")
    else:
        report.append("   ✓ No significant gaps! You're well-prepared.")

    # Effort impact
    report.append(f"\n EFFORT-OUTCOME ANALYSIS")
    efforts = calculate_effort_with_diminishing_returns(course_key, student_ratings)
    report.append(f"   How effort affects performance:")
    for effort in efforts:
        bar_length = int(effort['performance'] * 20)
        bar = "█" * bar_length + "░" * (20 - bar_length)
        report.append(f"   {effort['hours']:2d} hrs: {bar} {round(effort['performance']*100, 1)}%")

    # Uncertainty
    uncertainty = calculate_performance_uncertainty(course_key, student_ratings, study_hours)
    report.append(f"\n PERFORMANCE UNCERTAINTY")
    report.append(f"   Base Prediction: {round(uncertainty['base_performance']*100, 1)}%")
    report.append(f"   Expected Range (±1σ): {round(uncertainty['range_1sigma'][0]*100, 1)}% - {round(uncertainty['range_1sigma'][1]*100, 1)}%")
    report.append(f"   Wider Range (±2σ): {round(uncertainty['range_2sigma'][0]*100, 1)}% - {round(uncertainty['range_2sigma'][1]*100, 1)}%")
    report.append(f"   Uncertainty Level: {round(uncertainty['std_deviation']*100, 1)}% (σ)")

    # Comparison with other recommendations
    if len(top_2_courses) > 1 and course_key in top_2_courses:
        report.append(f"\n COMPARISON WITH OTHER RECOMMENDATIONS")
        for other_course in top_2_courses:
            if other_course != course_key:
                other_suit = calculate_suitability_score(other_course, student_ratings)
                diff = (suitability - other_suit) * 100
                if diff > 0:
                    report.append(f"   vs {other_course}: +{round(diff, 1)}% better suitability")
                else:
                    report.append(f"   vs {other_course}: {round(diff, 1)}% lower suitability")

    report.append("\n" + "="*70 + "\n")
    return "\n".join(report)

def save_session_history(student_name, course_key, student_ratings, study_hours, scores):
    """Save session to JSON history for future analysis"""
    history_file = f"session_history_{student_name}_{datetime.now().strftime('%Y%m%d')}.json"

    session_data = {
        "timestamp": datetime.now().isoformat(),
        "student_name": student_name,
        "selected_course": course_key,
        "course_name": courses.get(course_key, "Unknown"),
        "student_ratings": student_ratings,
        "study_hours": study_hours,
        "scores": scores
    }

    # Try to load existing history
    try:
        if Path(history_file).exists():
            with open(history_file, 'r') as f:
                history = json.load(f)
    except:
        history = []

    # Save to file
    try:
        with open(history_file, 'w') as f:
            json.dump(history, f, indent=2)
        print(f" Session saved to: {history_file}")
    except Exception as e:
        print(f" Could not save session history: {e}")

print("\n" + "="*70)
print("🎓 INTELLIGENT ACADEMIC DECISION SUPPORT SYSTEM")
print("="*70)
print("\nWelcome to the Course Recommendation Engine!")
print("This system analyzes your skills and recommends the best courses for you.\n")

# Get student name
student_name = input(" Enter your name: ").strip()
if not student_name:
    student_name = "Student"
print(f"Hello, {student_name}! \n")

# Display available courses
print("="*70)
print(" AVAILABLE COURSES (50+ OPTIONS)")
print("="*70)
for i, (code, name) in enumerate(courses.items(), 1):
    print(f"{i:2d}. {name} ({code})")
    if i % 5 == 0:
        print()

print("\n" + "="*70)
selected_course_key = None
while not selected_course_key:
    course_input = input("🔍 Enter course code or name: ").strip().upper()

    # Check exact code match
    if course_input in courses:
        selected_course_key = course_input
    else:
        # Check name match
        for code, name in courses.items():
            if name.upper() == course_input:
                selected_course_key = code
                break

    if not selected_course_key:
        print(f" '{course_input}' not found. Please enter a valid code or name.")
        print(" Try again with exact name or code...\n")

print(f"\n Selected: {courses[selected_course_key]}\n")

# Get student ratings for course subjects
print("="*70)
print(" RATE YOUR SKILLS IN COURSE SUBJECTS")
print("="*70)
print(" Instructions:")
print("   • Rate from 0 (No knowledge) to 5 (Expert level)")
print("   • Be honest for accurate recommendations\n")

student_ratings = {}
course_subs = course_subjects.get(selected_course_key, [])

for subject in course_subs:
    rating = get_valid_rating(f"   {subject}: ")
    student_ratings[subject] = rating

print(f"\n Ratings recorded for {len(student_ratings)} subjects\n")

# Get study hours
print("="*70)
print("⏱️ STUDY COMMITMENT")
print("="*70)
study_hours = get_valid_hours("How many hours per day can you study? (2-10): ")
print(f" Study commitment: {study_hours} hours/day\n")

# =====================================================================
# MODULE 1: COURSE SUITABILITY SCORING
# =====================================================================
print("="*70)
print(" MODULE 1: COURSE SUITABILITY ANALYSIS")
print("="*70)
print(" Analyzing all 50+ courses for you...\n")

all_suitability_scores = {}
for course_code in courses.keys():
    score = calculate_suitability_score(course_code, student_ratings)
    all_suitability_scores[course_code] = score

# Get top 2 courses
top_2_courses = sorted(all_suitability_scores.keys(),
                       key=lambda x: all_suitability_scores[x],
                       reverse=True)[:2]

print(" TOP 2 RECOMMENDED COURSES:\n")
for rank, course_code in enumerate(top_2_courses, 1):
    score = all_suitability_scores[course_code]
    print(f"{rank}. {courses[course_code]}")
    print(f"   Code: {course_code}")
    print(f"   Suitability Score: {round(score*100, 1)}%")
    bar_length = int(score * 20)
    bar = "█" * bar_length + "░" * (20 - bar_length)
    print(f"   {bar}\n")

print("="*70)
print(" MODULE 2: ACADEMIC RISK PREDICTION")
print("="*70)
print(" Analyzing success probability and identifying risks...\n")

for course_code in top_2_courses:
    risk_info = calculate_risk_prediction(course_code, student_ratings, study_hours)
    print(f" {courses[course_code]}")
    print(f"   Risk Level: {risk_info['level']}")
    print(f"   Risk Score: {round(risk_info['score']*100, 1)}%")
    print(f"   Status: {risk_info['description']}\n")

# =====================================================================
# MODULE 3: EFFORT-OUTCOME ANALYSIS
# =====================================================================
print("="*70)
print(" MODULE 3: EFFORT-OUTCOME ANALYSIS (DIMINISHING RETURNS)")
print("="*70)
print(" Calculating how study effort affects performance...\n")

for course_code in top_2_courses:
    print(f" {courses[course_code]}")
    print("   Study Hours → Expected Performance:\n")

    efforts = calculate_effort_with_diminishing_returns(course_code, student_ratings)
    for effort in efforts:
        perf = effort['performance']
        bar_length = int(perf * 15)
        bar = "█" * bar_length + "░" * (15 - bar_length)
        print(f"   {effort['hours']:2d} hrs/day: {bar} {round(perf*100, 1)}%")
    print()

# =====================================================================
# MODULE 4: PREREQUISITE GAP ANALYSIS
# =====================================================================
print("="*70)
print(" MODULE 4: PREREQUISITE GAP ANALYSIS (PRIORITY-RANKED)")
print("="*70)
print(" Identifying knowledge gaps and prioritizing learning...\n")

for course_code in top_2_courses:
    print(f" {courses[course_code]}\n")

    gaps = identify_knowledge_gaps(course_code, student_ratings)
    if gaps:
        print(f"   Total Gaps: {len(gaps)}\n")
        for i, gap in enumerate(gaps, 1):
            print(f"   {i}. {gap['subject']}")
            print(f"      Required: {gap['required']}/5 | Your Level: {gap['student']}/5 | Gap: {gap['gap']}")
            print(f"      Priority Score: {round(gap['priority'], 3)} (Importance: {round(gap['importance']*100, 1)}%)")
            print()
    else:
        print("    No significant gaps! You're well-prepared.\n")

# =====================================================================
# MODULE 5: PERFORMANCE UNCERTAINTY ESTIMATION
# =====================================================================
print("="*70)
print(" MODULE 5: PERFORMANCE UNCERTAINTY ESTIMATION")
print("="*70)
print(" Simulating 1000 scenarios with realistic variance (σ=15%)...\n")

for course_code in top_2_courses:
    uncertainty = calculate_performance_uncertainty(course_code, student_ratings, study_hours)
    print(f" {courses[course_code]}")
    print(f"   Base Prediction: {round(uncertainty['base_performance']*100, 1)}%")
    print(f"   Expected Range (68% confidence, ±1σ): {round(uncertainty['range_1sigma'][0]*100, 1)}% - {round(uncertainty['range_1sigma'][1]*100, 1)}%")
    print(f"   Wider Range (95% confidence, ±2σ): {round(uncertainty['range_2sigma'][0]*100, 1)}% - {round(uncertainty['range_2sigma'][1]*100, 1)}%")
    print(f"   Sample Observed Min-Max: {round(uncertainty['samples_min']*100, 1)}% - {round(uncertainty['samples_max']*100, 1)}%\n")

print("="*70)
print(" MODULE 6: DECISION FUSION (FINAL RECOMMENDATION)")
print("="*70)
print(" Combining all analyses for holistic recommendation...\n")

fusion_scores = {}
for course_code in top_2_courses:
    fusion = calculate_fusion_score(course_code, student_ratings, study_hours)
    fusion_scores[course_code] = fusion

    print(f" {courses[course_code]}")
    print(f"   Final Fusion Score: {round(fusion['final_score']*100, 1)}%")
    print(f"   • Suitability ({WEIGHT_SUITABILITY*100:.0f}%): {round(fusion['suitability_component']*100, 1)}%")
    print(f"   • Risk ({WEIGHT_RISK*100:.0f}%): {round(fusion['risk_component']*100, 1)}%")
    print(f"   • Gaps ({WEIGHT_GAPS*100:.0f}%): {round(fusion['gap_component']*100, 1)}%")
    bar_length = int(fusion['final_score'] * 20)
    bar = "█" * bar_length + "░" * (20 - bar_length)
    print(f"   {bar}\n")

print("="*70)
print(" MODULE 7: DETAILED EXPLAINABILITY REPORTS")
print("="*70)

for course_code in top_2_courses:
    report = generate_explainability_report(course_code, student_ratings, study_hours, top_2_courses)
    print(report)

print("="*70)
print(" FINAL RECOMMENDATION")
print("="*70)

best_course = max(fusion_scores.keys(), key=lambda x: fusion_scores[x]['final_score'])
best_score = fusion_scores[best_course]['final_score']

print(f"\n BEST MATCH FOR {student_name.upper()}:")
print(f"   {courses[best_course]}")
print(f"   Final Score: {round(best_score*100, 1)}%\n")

if best_score > 0.75:
    print(" This course is an EXCELLENT match for you!")
    print(" You have the skills needed to succeed.")
elif best_score > 0.55:
    print(" This course is a GOOD match for you!")
    print(" Focus on bridging identified knowledge gaps.")
else:
    print(" This course presents MODERATE challenges.")
    print(" Significant preparation may be needed.")

# Save session history
scores_summary = {
    "suitability": round(all_suitability_scores[best_course]*100, 1),
    "risk_level": calculate_risk_prediction(best_course, student_ratings, study_hours)['level'],
    "fusion_score": round(best_score*100, 1),
    "total_gaps": len(identify_knowledge_gaps(best_course, student_ratings))
}


print("\n" + "="*70)
print(" ANALYSIS COMPLETE!")
print("="*70)
print("\n Thank you for using the Intelligent Academic Decision Support System!")
print(" For questions or feedback, contact your academic advisor.\n")